version: '3.8'

services:
  web:
    build: .
    container_name: project2_web
    ports:
      - "5002:80"
    depends_on:
      - db
    networks:
      - project2-net

  db:
    image: mariadb:10.6
    container_name: project2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project2_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      # This volume mounts the init.sql file to initialize the database on first run
      - ./db_setup:/docker-entrypoint-initdb.d
    networks:
      - project2-net

networks:
  project2-net: